AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/hello
      Runtime: go1.x
      CodeUri: .
      MemorySize: 128
      Timeout: 100
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
